# Generated by Django 4.2.2 on 2023-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imgs')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('fruit_output', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
