# Generated by Django 4.2.2 on 2023-06-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_storage',
            old_name='ocr_output',
            new_name='fruit_output',
        ),
    ]
